---
# 后端服务
apiVersion: v1
kind: Service
metadata:
  name: image-tools-api-backend-service
  namespace: aigchub-prod
  labels:
    app: image-tools-api-backend
    component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 58888
      protocol: TCP
  selector:
    app: image-tools-api-backend

---
# 前端服务
apiVersion: v1
kind: Service
metadata:
  name: image-tools-api-frontend-service
  namespace: aigchub-prod
  labels:
    app: image-tools-api-frontend
    component: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: image-tools-api-frontend
